### ISSUE TITLE
Mismatch in required GraphLab Create version

### ISSUE THREAD

**Issue by znation** [learnml/machine-learning-specialization#17]
In the course materials for Course 3 Classification (pre-quiz on week 2) it says:

> Make sure that you are using GraphLab Create 1.8.3. See this post for installing the correct version of GraphLab Create.

But inside the notebook itself it says:

> Make sure you have the latest version of GraphLab Create. Upgrade by
>   `pip install graphlab-create --upgrade`
> See this page for detailed instructions on upgrading.

The latest version of GraphLab Create is 1.9. Which version is required for this course -- either? If we are going to be this explicit about version it should agree in both places.

**Comment by dtrebbien** [comment]
A topic was posted about `module-5-decision-tree-assignment-1.ipynb` in the Course 3 discussion forums:
https://www.coursera.org/learn/ml-classification/discussions/weeks/3/threads/xUmEgCt7Eeakfw5ltszKlw
There may be slight differences in results when using GLC 1.9 (I haven't verified, though).

**Comment by dtrebbien** [comment]
Another thread came up regarding which GLC version to use:
https://www.coursera.org/learn/ml-classification/discussions/weeks/2/threads/lvc4xi1wEeaKAhJC1hWxEQ

**Comment by dtrebbien** [comment]
Now that it is no longer possible to downgrade to 1.8.3, there have been a couple of threads in the discussion forums asking about this:

 * https://www.coursera.org/learn/ml-classification/discussions/all/threads/Lp6ED1bSEeaydQoIWAk_aQ
 * https://www.coursera.org/learn/ml-classification/discussions/all/threads/a0YRhF0REeaqcg4GrDfwQQ

**Comment by hcho3** [comment]
We finished testing all notebooks with GraphLab Create 2.1. All references to 1.8.3 have been removed.
