### ISSUE TITLE
Smart initialization uses distance rather than squared distance

### ISSUE THREAD

**Issue by eyurtsev** [learnml/machine-learning-specialization#30]
I doubt this affects the end result much, but the implementation uses distance rather than squared distance in contrast with the comment (and the definition on wikipedia).I think that proportionality is usually used to imply linear dependence, hence:

p = a * d + b -> proportional to distance
p = a * d^2 + b -> proportional to squared distance

```
        # Choose the next centroid randomly, so that the probability for each data point to be chosen
        # is directly proportional to its squared distance from the nearest centroid.
        # Roughtly speaking, a new centroid should be as far as from ohter centroids as possible.
        idx = np.random.choice(data.shape[0], 1, p=distances/sum(distances))
```

**Comment by hcho3** [comment]
[This commit](https://github.com/learnml/machine-learning-specialization/commit/e8c78fe7c649b801302de5b7fff07f1b359aa43b) fixes the said issue. Thanks for reporting it, and sorry for not responding earlier.
