### ISSUE TITLE
Transposed equation terms in starter code instructions.

### ISSUE THREAD

**Issue by FCH808** [learnml/machine-learning-specialization#5]
In [`week-1-simple-regression-assignment-blank.ipynb` I noticed that the simple regression formula in the starter code instructions is incorrect.] (https://github.com/learnml/machine-learning-specialization/commit/e17ff2f199c88330603b3412b11e74f113f82396#diff-a76db285248dcacf6f98b74c2e9dc761R385) 

It states:
**_solve output = slope + intercept*input_feature for input_feature_**
when it should be:
 **_solve output =  intercept + slope*input_feature for input_feature_**. 

I'd like to update it. Is this a welcome contribution right now?

**Comment by hcho3** [comment]
We made the fix. Thank you!
