### ISSUE TITLE
Course 2 Notebook issues

### ISSUE THREAD

**Issue by rschindlauer** [learnml/machine-learning-specialization#6]
In the [regression introduction notebook for course 2](https://github.com/learnml/machine-learning-specialization/blob/master/course-2/week-1-simple-regression-assignment-blank.ipynb) I believe these comment should suggest `sum` instead of `mean`:
```
    # compute the product of the output and the input_feature and its mean    
    # compute the squared value of the input_feature and its mean
```
Also, there are a few typos in this notebook:

soltion => solution
slop => slope
coses => costs
squarfeet => squarefeet

**Comment by hcho3** [comment]
We fixed the typos and updated the instructions to be consistent with the formulas given in the lecture. Thank you!
